---
title: Pray to Play?
author: Sophie Hill
date: '2020-11-16'
slug: pray-to-play
categories: []
tags: ['dataviz', 'networks']
# subtitle: 'Examining COVID contracts linked to the Plymouth Brethren Christian Church'
summary: ''
authors: []
lastmod: '2020-11-16T21:21:39-05:00'
featured: no
draft: false
# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image: 
  caption: ""
  focal_point: ""
  preview_only: true
projects: []
---

Following on from the original [My Little Crony](https://www.sophie-e-hill.com/post/my-little-crony/) map, this visualization zooms in on the government contracts being awarded to firms **linked to an Evangelical Christian sect**: the Plymouth Brethren Christian Church.

Investigative reporting by [Byline Times](https://bylinetimes.com/2020/11/18/plymouth-exclusive-brethren-ppe-contracts-uk-government/) and the non-profit group [All the Citizens](https://twitter.com/allthecitizens/status/1329069371709222913?s=20) has uncovered **21 UK companies** that appear to have links to the Plymouth Brethren, which have won at least **49 Covid-related government contracts** since March, **worth as much as £1.1 billion**.


<p align="center"><iframe style="border: 0; width:100%; height:700px; overflow:hidden;" src="/files/pbcc.html"></iframe></p>
    
## Guide
- *Scroll* to zoom
- *Drag* to move around
- *Hover* or *tap* icons and connections for more info
- Use the *drop down menu* to select highlight particular nodes

The lines represent:

<span style="color: red;"> &horbar; government contracts</span> \
<span style="color: grey;">&horbar; other connections (e.g. family/employment)</span> 

   
Thicker lines indicate more valuable contracts or donations.

